/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.validation;

import nl.tno.torxakis.language.validation.AbstractTorXakisDslValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class TorXakisDslValidator extends AbstractTorXakisDslValidator {
}
