/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl.impl;

import nl.tno.torxakis.language.torXakisDsl.ChannelDef;
import nl.tno.torxakis.language.torXakisDsl.ChannelDefName;
import nl.tno.torxakis.language.torXakisDsl.NeChannelsDeclList;
import nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Channel Def</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ChannelDefImpl#getName <em>Name</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ChannelDefImpl#getNeChannelDeclList <em>Ne Channel Decl List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ChannelDefImpl extends MinimalEObjectImpl.Container implements ChannelDef
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected ChannelDefName name;

  /**
   * The cached value of the '{@link #getNeChannelDeclList() <em>Ne Channel Decl List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNeChannelDeclList()
   * @generated
   * @ordered
   */
  protected NeChannelsDeclList neChannelDeclList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ChannelDefImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TorXakisDslPackage.Literals.CHANNEL_DEF;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChannelDefName getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(ChannelDefName newName, NotificationChain msgs)
  {
    ChannelDefName oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.CHANNEL_DEF__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(ChannelDefName newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.CHANNEL_DEF__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.CHANNEL_DEF__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.CHANNEL_DEF__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeChannelsDeclList getNeChannelDeclList()
  {
    return neChannelDeclList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNeChannelDeclList(NeChannelsDeclList newNeChannelDeclList, NotificationChain msgs)
  {
    NeChannelsDeclList oldNeChannelDeclList = neChannelDeclList;
    neChannelDeclList = newNeChannelDeclList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.CHANNEL_DEF__NE_CHANNEL_DECL_LIST, oldNeChannelDeclList, newNeChannelDeclList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNeChannelDeclList(NeChannelsDeclList newNeChannelDeclList)
  {
    if (newNeChannelDeclList != neChannelDeclList)
    {
      NotificationChain msgs = null;
      if (neChannelDeclList != null)
        msgs = ((InternalEObject)neChannelDeclList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.CHANNEL_DEF__NE_CHANNEL_DECL_LIST, null, msgs);
      if (newNeChannelDeclList != null)
        msgs = ((InternalEObject)newNeChannelDeclList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.CHANNEL_DEF__NE_CHANNEL_DECL_LIST, null, msgs);
      msgs = basicSetNeChannelDeclList(newNeChannelDeclList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.CHANNEL_DEF__NE_CHANNEL_DECL_LIST, newNeChannelDeclList, newNeChannelDeclList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CHANNEL_DEF__NAME:
        return basicSetName(null, msgs);
      case TorXakisDslPackage.CHANNEL_DEF__NE_CHANNEL_DECL_LIST:
        return basicSetNeChannelDeclList(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CHANNEL_DEF__NAME:
        return getName();
      case TorXakisDslPackage.CHANNEL_DEF__NE_CHANNEL_DECL_LIST:
        return getNeChannelDeclList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CHANNEL_DEF__NAME:
        setName((ChannelDefName)newValue);
        return;
      case TorXakisDslPackage.CHANNEL_DEF__NE_CHANNEL_DECL_LIST:
        setNeChannelDeclList((NeChannelsDeclList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CHANNEL_DEF__NAME:
        setName((ChannelDefName)null);
        return;
      case TorXakisDslPackage.CHANNEL_DEF__NE_CHANNEL_DECL_LIST:
        setNeChannelDeclList((NeChannelsDeclList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CHANNEL_DEF__NAME:
        return name != null;
      case TorXakisDslPackage.CHANNEL_DEF__NE_CHANNEL_DECL_LIST:
        return neChannelDeclList != null;
    }
    return super.eIsSet(featureID);
  }

} //ChannelDefImpl
