/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl.impl;

import nl.tno.torxakis.language.torXakisDsl.Constructor;
import nl.tno.torxakis.language.torXakisDsl.ConstructorName;
import nl.tno.torxakis.language.torXakisDsl.NeFieldList;
import nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Constructor</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ConstructorImpl#getName <em>Name</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ConstructorImpl#getNeFieldsList <em>Ne Fields List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ConstructorImpl extends MinimalEObjectImpl.Container implements Constructor
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected ConstructorName name;

  /**
   * The cached value of the '{@link #getNeFieldsList() <em>Ne Fields List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNeFieldsList()
   * @generated
   * @ordered
   */
  protected NeFieldList neFieldsList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ConstructorImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TorXakisDslPackage.Literals.CONSTRUCTOR;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConstructorName getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(ConstructorName newName, NotificationChain msgs)
  {
    ConstructorName oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.CONSTRUCTOR__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(ConstructorName newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.CONSTRUCTOR__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.CONSTRUCTOR__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.CONSTRUCTOR__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeFieldList getNeFieldsList()
  {
    return neFieldsList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNeFieldsList(NeFieldList newNeFieldsList, NotificationChain msgs)
  {
    NeFieldList oldNeFieldsList = neFieldsList;
    neFieldsList = newNeFieldsList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.CONSTRUCTOR__NE_FIELDS_LIST, oldNeFieldsList, newNeFieldsList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNeFieldsList(NeFieldList newNeFieldsList)
  {
    if (newNeFieldsList != neFieldsList)
    {
      NotificationChain msgs = null;
      if (neFieldsList != null)
        msgs = ((InternalEObject)neFieldsList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.CONSTRUCTOR__NE_FIELDS_LIST, null, msgs);
      if (newNeFieldsList != null)
        msgs = ((InternalEObject)newNeFieldsList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.CONSTRUCTOR__NE_FIELDS_LIST, null, msgs);
      msgs = basicSetNeFieldsList(newNeFieldsList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.CONSTRUCTOR__NE_FIELDS_LIST, newNeFieldsList, newNeFieldsList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CONSTRUCTOR__NAME:
        return basicSetName(null, msgs);
      case TorXakisDslPackage.CONSTRUCTOR__NE_FIELDS_LIST:
        return basicSetNeFieldsList(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CONSTRUCTOR__NAME:
        return getName();
      case TorXakisDslPackage.CONSTRUCTOR__NE_FIELDS_LIST:
        return getNeFieldsList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CONSTRUCTOR__NAME:
        setName((ConstructorName)newValue);
        return;
      case TorXakisDslPackage.CONSTRUCTOR__NE_FIELDS_LIST:
        setNeFieldsList((NeFieldList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CONSTRUCTOR__NAME:
        setName((ConstructorName)null);
        return;
      case TorXakisDslPackage.CONSTRUCTOR__NE_FIELDS_LIST:
        setNeFieldsList((NeFieldList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.CONSTRUCTOR__NAME:
        return name != null;
      case TorXakisDslPackage.CONSTRUCTOR__NE_FIELDS_LIST:
        return neFieldsList != null;
    }
    return super.eIsSet(featureID);
  }

} //ConstructorImpl
