/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl.impl;

import nl.tno.torxakis.language.torXakisDsl.ExitDecl;
import nl.tno.torxakis.language.torXakisDsl.NeTypeNameList;
import nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Exit Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ExitDeclImpl#getExit <em>Exit</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ExitDeclImpl#getNeTypeNameList <em>Ne Type Name List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ExitDeclImpl extends MinimalEObjectImpl.Container implements ExitDecl
{
  /**
   * The default value of the '{@link #getExit() <em>Exit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExit()
   * @generated
   * @ordered
   */
  protected static final String EXIT_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getExit() <em>Exit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExit()
   * @generated
   * @ordered
   */
  protected String exit = EXIT_EDEFAULT;

  /**
   * The cached value of the '{@link #getNeTypeNameList() <em>Ne Type Name List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNeTypeNameList()
   * @generated
   * @ordered
   */
  protected NeTypeNameList neTypeNameList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ExitDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TorXakisDslPackage.Literals.EXIT_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getExit()
  {
    return exit;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setExit(String newExit)
  {
    String oldExit = exit;
    exit = newExit;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.EXIT_DECL__EXIT, oldExit, exit));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeTypeNameList getNeTypeNameList()
  {
    return neTypeNameList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNeTypeNameList(NeTypeNameList newNeTypeNameList, NotificationChain msgs)
  {
    NeTypeNameList oldNeTypeNameList = neTypeNameList;
    neTypeNameList = newNeTypeNameList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.EXIT_DECL__NE_TYPE_NAME_LIST, oldNeTypeNameList, newNeTypeNameList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNeTypeNameList(NeTypeNameList newNeTypeNameList)
  {
    if (newNeTypeNameList != neTypeNameList)
    {
      NotificationChain msgs = null;
      if (neTypeNameList != null)
        msgs = ((InternalEObject)neTypeNameList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.EXIT_DECL__NE_TYPE_NAME_LIST, null, msgs);
      if (newNeTypeNameList != null)
        msgs = ((InternalEObject)newNeTypeNameList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.EXIT_DECL__NE_TYPE_NAME_LIST, null, msgs);
      msgs = basicSetNeTypeNameList(newNeTypeNameList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.EXIT_DECL__NE_TYPE_NAME_LIST, newNeTypeNameList, newNeTypeNameList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.EXIT_DECL__NE_TYPE_NAME_LIST:
        return basicSetNeTypeNameList(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.EXIT_DECL__EXIT:
        return getExit();
      case TorXakisDslPackage.EXIT_DECL__NE_TYPE_NAME_LIST:
        return getNeTypeNameList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.EXIT_DECL__EXIT:
        setExit((String)newValue);
        return;
      case TorXakisDslPackage.EXIT_DECL__NE_TYPE_NAME_LIST:
        setNeTypeNameList((NeTypeNameList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.EXIT_DECL__EXIT:
        setExit(EXIT_EDEFAULT);
        return;
      case TorXakisDslPackage.EXIT_DECL__NE_TYPE_NAME_LIST:
        setNeTypeNameList((NeTypeNameList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.EXIT_DECL__EXIT:
        return EXIT_EDEFAULT == null ? exit != null : !EXIT_EDEFAULT.equals(exit);
      case TorXakisDslPackage.EXIT_DECL__NE_TYPE_NAME_LIST:
        return neTypeNameList != null;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (exit: ");
    result.append(exit);
    result.append(')');
    return result.toString();
  }

} //ExitDeclImpl
