/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl.impl;

import nl.tno.torxakis.language.torXakisDsl.IdName;
import nl.tno.torxakis.language.torXakisDsl.InitItem;
import nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage;
import nl.tno.torxakis.language.torXakisDsl.UpdateList;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Init Item</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.InitItemImpl#getIdName <em>Id Name</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.InitItemImpl#getUpdateList <em>Update List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class InitItemImpl extends MinimalEObjectImpl.Container implements InitItem
{
  /**
   * The cached value of the '{@link #getIdName() <em>Id Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getIdName()
   * @generated
   * @ordered
   */
  protected IdName idName;

  /**
   * The cached value of the '{@link #getUpdateList() <em>Update List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getUpdateList()
   * @generated
   * @ordered
   */
  protected UpdateList updateList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected InitItemImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TorXakisDslPackage.Literals.INIT_ITEM;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IdName getIdName()
  {
    return idName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetIdName(IdName newIdName, NotificationChain msgs)
  {
    IdName oldIdName = idName;
    idName = newIdName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.INIT_ITEM__ID_NAME, oldIdName, newIdName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setIdName(IdName newIdName)
  {
    if (newIdName != idName)
    {
      NotificationChain msgs = null;
      if (idName != null)
        msgs = ((InternalEObject)idName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.INIT_ITEM__ID_NAME, null, msgs);
      if (newIdName != null)
        msgs = ((InternalEObject)newIdName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.INIT_ITEM__ID_NAME, null, msgs);
      msgs = basicSetIdName(newIdName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.INIT_ITEM__ID_NAME, newIdName, newIdName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UpdateList getUpdateList()
  {
    return updateList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetUpdateList(UpdateList newUpdateList, NotificationChain msgs)
  {
    UpdateList oldUpdateList = updateList;
    updateList = newUpdateList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.INIT_ITEM__UPDATE_LIST, oldUpdateList, newUpdateList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setUpdateList(UpdateList newUpdateList)
  {
    if (newUpdateList != updateList)
    {
      NotificationChain msgs = null;
      if (updateList != null)
        msgs = ((InternalEObject)updateList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.INIT_ITEM__UPDATE_LIST, null, msgs);
      if (newUpdateList != null)
        msgs = ((InternalEObject)newUpdateList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.INIT_ITEM__UPDATE_LIST, null, msgs);
      msgs = basicSetUpdateList(newUpdateList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.INIT_ITEM__UPDATE_LIST, newUpdateList, newUpdateList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.INIT_ITEM__ID_NAME:
        return basicSetIdName(null, msgs);
      case TorXakisDslPackage.INIT_ITEM__UPDATE_LIST:
        return basicSetUpdateList(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.INIT_ITEM__ID_NAME:
        return getIdName();
      case TorXakisDslPackage.INIT_ITEM__UPDATE_LIST:
        return getUpdateList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.INIT_ITEM__ID_NAME:
        setIdName((IdName)newValue);
        return;
      case TorXakisDslPackage.INIT_ITEM__UPDATE_LIST:
        setUpdateList((UpdateList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.INIT_ITEM__ID_NAME:
        setIdName((IdName)null);
        return;
      case TorXakisDslPackage.INIT_ITEM__UPDATE_LIST:
        setUpdateList((UpdateList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.INIT_ITEM__ID_NAME:
        return idName != null;
      case TorXakisDslPackage.INIT_ITEM__UPDATE_LIST:
        return updateList != null;
    }
    return super.eIsSet(featureID);
  }

} //InitItemImpl
