/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl.impl;

import java.util.Collection;

import nl.tno.torxakis.language.torXakisDsl.ChannelDefs;
import nl.tno.torxakis.language.torXakisDsl.CnectDef;
import nl.tno.torxakis.language.torXakisDsl.ConstDefs;
import nl.tno.torxakis.language.torXakisDsl.FuncDefs;
import nl.tno.torxakis.language.torXakisDsl.MapperDef;
import nl.tno.torxakis.language.torXakisDsl.Model;
import nl.tno.torxakis.language.torXakisDsl.ModelDef;
import nl.tno.torxakis.language.torXakisDsl.ProcDefs;
import nl.tno.torxakis.language.torXakisDsl.StautDefs;
import nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage;
import nl.tno.torxakis.language.torXakisDsl.TypeDefs;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Model</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ModelImpl#getTypeDefs <em>Type Defs</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ModelImpl#getFuncDefs <em>Func Defs</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ModelImpl#getConstDefs <em>Const Defs</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ModelImpl#getProcDefs <em>Proc Defs</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ModelImpl#getStautDefs <em>Staut Defs</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ModelImpl#getChannelDefs <em>Channel Defs</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ModelImpl#getModelDef <em>Model Def</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ModelImpl#getMapperDef <em>Mapper Def</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ModelImpl#getCnectDef <em>Cnect Def</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ModelImpl extends MinimalEObjectImpl.Container implements Model
{
  /**
   * The cached value of the '{@link #getTypeDefs() <em>Type Defs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeDefs()
   * @generated
   * @ordered
   */
  protected EList<TypeDefs> typeDefs;

  /**
   * The cached value of the '{@link #getFuncDefs() <em>Func Defs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getFuncDefs()
   * @generated
   * @ordered
   */
  protected EList<FuncDefs> funcDefs;

  /**
   * The cached value of the '{@link #getConstDefs() <em>Const Defs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getConstDefs()
   * @generated
   * @ordered
   */
  protected EList<ConstDefs> constDefs;

  /**
   * The cached value of the '{@link #getProcDefs() <em>Proc Defs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProcDefs()
   * @generated
   * @ordered
   */
  protected EList<ProcDefs> procDefs;

  /**
   * The cached value of the '{@link #getStautDefs() <em>Staut Defs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getStautDefs()
   * @generated
   * @ordered
   */
  protected EList<StautDefs> stautDefs;

  /**
   * The cached value of the '{@link #getChannelDefs() <em>Channel Defs</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getChannelDefs()
   * @generated
   * @ordered
   */
  protected EList<ChannelDefs> channelDefs;

  /**
   * The cached value of the '{@link #getModelDef() <em>Model Def</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getModelDef()
   * @generated
   * @ordered
   */
  protected EList<ModelDef> modelDef;

  /**
   * The cached value of the '{@link #getMapperDef() <em>Mapper Def</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMapperDef()
   * @generated
   * @ordered
   */
  protected EList<MapperDef> mapperDef;

  /**
   * The cached value of the '{@link #getCnectDef() <em>Cnect Def</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCnectDef()
   * @generated
   * @ordered
   */
  protected EList<CnectDef> cnectDef;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ModelImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TorXakisDslPackage.Literals.MODEL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<TypeDefs> getTypeDefs()
  {
    if (typeDefs == null)
    {
      typeDefs = new EObjectContainmentEList<TypeDefs>(TypeDefs.class, this, TorXakisDslPackage.MODEL__TYPE_DEFS);
    }
    return typeDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<FuncDefs> getFuncDefs()
  {
    if (funcDefs == null)
    {
      funcDefs = new EObjectContainmentEList<FuncDefs>(FuncDefs.class, this, TorXakisDslPackage.MODEL__FUNC_DEFS);
    }
    return funcDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ConstDefs> getConstDefs()
  {
    if (constDefs == null)
    {
      constDefs = new EObjectContainmentEList<ConstDefs>(ConstDefs.class, this, TorXakisDslPackage.MODEL__CONST_DEFS);
    }
    return constDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ProcDefs> getProcDefs()
  {
    if (procDefs == null)
    {
      procDefs = new EObjectContainmentEList<ProcDefs>(ProcDefs.class, this, TorXakisDslPackage.MODEL__PROC_DEFS);
    }
    return procDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<StautDefs> getStautDefs()
  {
    if (stautDefs == null)
    {
      stautDefs = new EObjectContainmentEList<StautDefs>(StautDefs.class, this, TorXakisDslPackage.MODEL__STAUT_DEFS);
    }
    return stautDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ChannelDefs> getChannelDefs()
  {
    if (channelDefs == null)
    {
      channelDefs = new EObjectContainmentEList<ChannelDefs>(ChannelDefs.class, this, TorXakisDslPackage.MODEL__CHANNEL_DEFS);
    }
    return channelDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<ModelDef> getModelDef()
  {
    if (modelDef == null)
    {
      modelDef = new EObjectContainmentEList<ModelDef>(ModelDef.class, this, TorXakisDslPackage.MODEL__MODEL_DEF);
    }
    return modelDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<MapperDef> getMapperDef()
  {
    if (mapperDef == null)
    {
      mapperDef = new EObjectContainmentEList<MapperDef>(MapperDef.class, this, TorXakisDslPackage.MODEL__MAPPER_DEF);
    }
    return mapperDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<CnectDef> getCnectDef()
  {
    if (cnectDef == null)
    {
      cnectDef = new EObjectContainmentEList<CnectDef>(CnectDef.class, this, TorXakisDslPackage.MODEL__CNECT_DEF);
    }
    return cnectDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.MODEL__TYPE_DEFS:
        return ((InternalEList<?>)getTypeDefs()).basicRemove(otherEnd, msgs);
      case TorXakisDslPackage.MODEL__FUNC_DEFS:
        return ((InternalEList<?>)getFuncDefs()).basicRemove(otherEnd, msgs);
      case TorXakisDslPackage.MODEL__CONST_DEFS:
        return ((InternalEList<?>)getConstDefs()).basicRemove(otherEnd, msgs);
      case TorXakisDslPackage.MODEL__PROC_DEFS:
        return ((InternalEList<?>)getProcDefs()).basicRemove(otherEnd, msgs);
      case TorXakisDslPackage.MODEL__STAUT_DEFS:
        return ((InternalEList<?>)getStautDefs()).basicRemove(otherEnd, msgs);
      case TorXakisDslPackage.MODEL__CHANNEL_DEFS:
        return ((InternalEList<?>)getChannelDefs()).basicRemove(otherEnd, msgs);
      case TorXakisDslPackage.MODEL__MODEL_DEF:
        return ((InternalEList<?>)getModelDef()).basicRemove(otherEnd, msgs);
      case TorXakisDslPackage.MODEL__MAPPER_DEF:
        return ((InternalEList<?>)getMapperDef()).basicRemove(otherEnd, msgs);
      case TorXakisDslPackage.MODEL__CNECT_DEF:
        return ((InternalEList<?>)getCnectDef()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.MODEL__TYPE_DEFS:
        return getTypeDefs();
      case TorXakisDslPackage.MODEL__FUNC_DEFS:
        return getFuncDefs();
      case TorXakisDslPackage.MODEL__CONST_DEFS:
        return getConstDefs();
      case TorXakisDslPackage.MODEL__PROC_DEFS:
        return getProcDefs();
      case TorXakisDslPackage.MODEL__STAUT_DEFS:
        return getStautDefs();
      case TorXakisDslPackage.MODEL__CHANNEL_DEFS:
        return getChannelDefs();
      case TorXakisDslPackage.MODEL__MODEL_DEF:
        return getModelDef();
      case TorXakisDslPackage.MODEL__MAPPER_DEF:
        return getMapperDef();
      case TorXakisDslPackage.MODEL__CNECT_DEF:
        return getCnectDef();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.MODEL__TYPE_DEFS:
        getTypeDefs().clear();
        getTypeDefs().addAll((Collection<? extends TypeDefs>)newValue);
        return;
      case TorXakisDslPackage.MODEL__FUNC_DEFS:
        getFuncDefs().clear();
        getFuncDefs().addAll((Collection<? extends FuncDefs>)newValue);
        return;
      case TorXakisDslPackage.MODEL__CONST_DEFS:
        getConstDefs().clear();
        getConstDefs().addAll((Collection<? extends ConstDefs>)newValue);
        return;
      case TorXakisDslPackage.MODEL__PROC_DEFS:
        getProcDefs().clear();
        getProcDefs().addAll((Collection<? extends ProcDefs>)newValue);
        return;
      case TorXakisDslPackage.MODEL__STAUT_DEFS:
        getStautDefs().clear();
        getStautDefs().addAll((Collection<? extends StautDefs>)newValue);
        return;
      case TorXakisDslPackage.MODEL__CHANNEL_DEFS:
        getChannelDefs().clear();
        getChannelDefs().addAll((Collection<? extends ChannelDefs>)newValue);
        return;
      case TorXakisDslPackage.MODEL__MODEL_DEF:
        getModelDef().clear();
        getModelDef().addAll((Collection<? extends ModelDef>)newValue);
        return;
      case TorXakisDslPackage.MODEL__MAPPER_DEF:
        getMapperDef().clear();
        getMapperDef().addAll((Collection<? extends MapperDef>)newValue);
        return;
      case TorXakisDslPackage.MODEL__CNECT_DEF:
        getCnectDef().clear();
        getCnectDef().addAll((Collection<? extends CnectDef>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.MODEL__TYPE_DEFS:
        getTypeDefs().clear();
        return;
      case TorXakisDslPackage.MODEL__FUNC_DEFS:
        getFuncDefs().clear();
        return;
      case TorXakisDslPackage.MODEL__CONST_DEFS:
        getConstDefs().clear();
        return;
      case TorXakisDslPackage.MODEL__PROC_DEFS:
        getProcDefs().clear();
        return;
      case TorXakisDslPackage.MODEL__STAUT_DEFS:
        getStautDefs().clear();
        return;
      case TorXakisDslPackage.MODEL__CHANNEL_DEFS:
        getChannelDefs().clear();
        return;
      case TorXakisDslPackage.MODEL__MODEL_DEF:
        getModelDef().clear();
        return;
      case TorXakisDslPackage.MODEL__MAPPER_DEF:
        getMapperDef().clear();
        return;
      case TorXakisDslPackage.MODEL__CNECT_DEF:
        getCnectDef().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.MODEL__TYPE_DEFS:
        return typeDefs != null && !typeDefs.isEmpty();
      case TorXakisDslPackage.MODEL__FUNC_DEFS:
        return funcDefs != null && !funcDefs.isEmpty();
      case TorXakisDslPackage.MODEL__CONST_DEFS:
        return constDefs != null && !constDefs.isEmpty();
      case TorXakisDslPackage.MODEL__PROC_DEFS:
        return procDefs != null && !procDefs.isEmpty();
      case TorXakisDslPackage.MODEL__STAUT_DEFS:
        return stautDefs != null && !stautDefs.isEmpty();
      case TorXakisDslPackage.MODEL__CHANNEL_DEFS:
        return channelDefs != null && !channelDefs.isEmpty();
      case TorXakisDslPackage.MODEL__MODEL_DEF:
        return modelDef != null && !modelDef.isEmpty();
      case TorXakisDslPackage.MODEL__MAPPER_DEF:
        return mapperDef != null && !mapperDef.isEmpty();
      case TorXakisDslPackage.MODEL__CNECT_DEF:
        return cnectDef != null && !cnectDef.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //ModelImpl
