/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl.impl;

import nl.tno.torxakis.language.torXakisDsl.*;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TorXakisDslFactoryImpl extends EFactoryImpl implements TorXakisDslFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TorXakisDslFactory init()
  {
    try
    {
      TorXakisDslFactory theTorXakisDslFactory = (TorXakisDslFactory)EPackage.Registry.INSTANCE.getEFactory(TorXakisDslPackage.eNS_URI);
      if (theTorXakisDslFactory != null)
      {
        return theTorXakisDslFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new TorXakisDslFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TorXakisDslFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case TorXakisDslPackage.MODEL: return createModel();
      case TorXakisDslPackage.TYPE_DEFS: return createTypeDefs();
      case TorXakisDslPackage.TYPE_DEF: return createTypeDef();
      case TorXakisDslPackage.FUNC_DEFS: return createFuncDefs();
      case TorXakisDslPackage.FUNC_DEF: return createFuncDef();
      case TorXakisDslPackage.CONST_DEFS: return createConstDefs();
      case TorXakisDslPackage.CONST_DEF: return createConstDef();
      case TorXakisDslPackage.PROC_DEFS: return createProcDefs();
      case TorXakisDslPackage.PROC_DEF: return createProcDef();
      case TorXakisDslPackage.STAUT_DEFS: return createStautDefs();
      case TorXakisDslPackage.STAUT_DEF: return createStautDef();
      case TorXakisDslPackage.CHANNEL_DEFS: return createChannelDefs();
      case TorXakisDslPackage.CHANNEL_DEF: return createChannelDef();
      case TorXakisDslPackage.MODEL_DEF: return createModelDef();
      case TorXakisDslPackage.MAPPER_DEF: return createMapperDef();
      case TorXakisDslPackage.CNECT_DEF: return createCnectDef();
      case TorXakisDslPackage.STAUT_ITEMS: return createStautItems();
      case TorXakisDslPackage.STATE_ITEM: return createStateItem();
      case TorXakisDslPackage.VAR_ITEM: return createVarItem();
      case TorXakisDslPackage.INIT_ITEM: return createInitItem();
      case TorXakisDslPackage.TRANS_ITEM: return createTransItem();
      case TorXakisDslPackage.TRANSITION: return createTransition();
      case TorXakisDslPackage.UPDATE_LIST: return createUpdateList();
      case TorXakisDslPackage.UPDATE: return createUpdate();
      case TorXakisDslPackage.MAPPER_NAME: return createMapperName();
      case TorXakisDslPackage.NE_CONSTRUCTOR_LIST: return createNeConstructorList();
      case TorXakisDslPackage.CONSTRUCTOR: return createConstructor();
      case TorXakisDslPackage.NE_FIELD_LIST: return createNeFieldList();
      case TorXakisDslPackage.FIELDS: return createFields();
      case TorXakisDslPackage.NE_FIELD_NAME_LIST: return createNeFieldNameList();
      case TorXakisDslPackage.FIELD_NAME: return createFieldName();
      case TorXakisDslPackage.EXIT_DECL: return createExitDecl();
      case TorXakisDslPackage.MODEL_NAME: return createModelName();
      case TorXakisDslPackage.CONNECTION_ITEM: return createConnectionItem();
      case TorXakisDslPackage.CONNECTION_OUT: return createConnectionOut();
      case TorXakisDslPackage.CONNECTION_IN: return createConnectionIn();
      case TorXakisDslPackage.ENCODING: return createEncoding();
      case TorXakisDslPackage.DECODING: return createDecoding();
      case TorXakisDslPackage.PORT_NUMBER: return createPortNumber();
      case TorXakisDslPackage.HOST_NAME: return createHostName();
      case TorXakisDslPackage.STAUT_NAME: return createStautName();
      case TorXakisDslPackage.CHANNEL_DEF_NAME: return createChannelDefName();
      case TorXakisDslPackage.PROC_NAME: return createProcName();
      case TorXakisDslPackage.CNECT_NAME: return createCnectName();
      case TorXakisDslPackage.NE_VARS_DECLARATION_LIST: return createNeVarsDeclarationList();
      case TorXakisDslPackage.VARS_DECLARATION: return createVarsDeclaration();
      case TorXakisDslPackage.NE_VAR_DECL_LIST: return createNeVarDeclList();
      case TorXakisDslPackage.VARS_DECL: return createVarsDecl();
      case TorXakisDslPackage.NE_CHANNELS_DECL_LIST: return createNeChannelsDeclList();
      case TorXakisDslPackage.CHANNELS_DECL: return createChannelsDecl();
      case TorXakisDslPackage.NE_TYPE_NAME_LIST: return createNeTypeNameList();
      case TorXakisDslPackage.TYPE_NAME: return createTypeName();
      case TorXakisDslPackage.NE_CHANNEL_NAME_LIST: return createNeChannelNameList();
      case TorXakisDslPackage.NE_ID_NAME_LIST: return createNeIdNameList();
      case TorXakisDslPackage.ID_NAME: return createIdName();
      case TorXakisDslPackage.CHANNEL_NAME: return createChannelName();
      case TorXakisDslPackage.NE_VAR_NAME_LIST: return createNeVarNameList();
      case TorXakisDslPackage.VAR_NAME: return createVarName();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR: return createProcessBehaviour();
      case TorXakisDslPackage.PROC_CALL: return createProcCall();
      case TorXakisDslPackage.NE_VAL_EXPR_LIST: return createNeValExprList();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_BRACKET: return createProcessBehaviourBracket();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_HIDE: return createProcessBehaviourHide();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_LET: return createProcessBehaviourLet();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_SEQUENCE: return createProcessBehaviourSequence();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_GUARDED: return createProcessBehaviourGuarded();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_STOP: return createProcessBehaviourStop();
      case TorXakisDslPackage.SYNCHRONIZED_CHANNELS: return createSynchronizedChannels();
      case TorXakisDslPackage.CONDITIONAL_COMMUNICATIONS: return createConditionalCommunications();
      case TorXakisDslPackage.COMMUNICATIONS: return createCommunications();
      case TorXakisDslPackage.COMMUNICATION: return createCommunication();
      case TorXakisDslPackage.CHANNEL_OFFER: return createChannelOffer();
      case TorXakisDslPackage.CONDITION: return createCondition();
      case TorXakisDslPackage.ASSIGNMENT: return createAssignment();
      case TorXakisDslPackage.VAR_DECL: return createVarDecl();
      case TorXakisDslPackage.VAL_EXPR: return createValExpr();
      case TorXakisDslPackage.VAL_EXPR2: return createValExpr2();
      case TorXakisDslPackage.VAL_EXPR_UNARY_OPERATOR: return createValExprUnaryOperator();
      case TorXakisDslPackage.SMALL_ID_NAME: return createSmallIdName();
      case TorXakisDslPackage.VAL_EXPR_ERROR: return createValExprError();
      case TorXakisDslPackage.VAL_EXPR_ITE: return createValExprIte();
      case TorXakisDslPackage.VAL_EXPR_LET: return createValExprLet();
      case TorXakisDslPackage.VAL_EXPR_BRACKET: return createValExprBracket();
      case TorXakisDslPackage.VAL_EXPR_REGEX: return createValExprRegex();
      case TorXakisDslPackage.VAL_EXPR_STRING: return createValExprString();
      case TorXakisDslPackage.VAL_EXPR_INTEGER: return createValExprInteger();
      case TorXakisDslPackage.VAL_EXPR_CONTRUCTOR_CALL: return createValExprContructorCall();
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL: return createValExprFunctionCall();
      case TorXakisDslPackage.VAL_EXPR_VAR: return createValExprVar();
      case TorXakisDslPackage.VAL_EXPR_CONST: return createValExprConst();
      case TorXakisDslPackage.CONSTRUCTOR_NAME: return createConstructorName();
      case TorXakisDslPackage.FUNC_NAME: return createFuncName();
      case TorXakisDslPackage.CONST_NAME: return createConstName();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_ENABLE: return createProcessBehaviourEnable();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_ENABLE_ACCEPT: return createProcessBehaviourEnableAccept();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_DISABLE: return createProcessBehaviourDisable();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_INTERRUPT: return createProcessBehaviourInterrupt();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_SYNCHRONIZED: return createProcessBehaviourSynchronized();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_PARALLEL: return createProcessBehaviourParallel();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_SYNCHRONIZE_CHANNELS: return createProcessBehaviourSynchronizeChannels();
      case TorXakisDslPackage.PROCESS_BEHAVIOUR_CHOICE: return createProcessBehaviourChoice();
      case TorXakisDslPackage.VAL_EXPR_OPERATOR: return createValExprOperator();
      case TorXakisDslPackage.VAL_EXPR_TEST: return createValExprTest();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Model createModel()
  {
    ModelImpl model = new ModelImpl();
    return model;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeDefs createTypeDefs()
  {
    TypeDefsImpl typeDefs = new TypeDefsImpl();
    return typeDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeDef createTypeDef()
  {
    TypeDefImpl typeDef = new TypeDefImpl();
    return typeDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FuncDefs createFuncDefs()
  {
    FuncDefsImpl funcDefs = new FuncDefsImpl();
    return funcDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FuncDef createFuncDef()
  {
    FuncDefImpl funcDef = new FuncDefImpl();
    return funcDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConstDefs createConstDefs()
  {
    ConstDefsImpl constDefs = new ConstDefsImpl();
    return constDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConstDef createConstDef()
  {
    ConstDefImpl constDef = new ConstDefImpl();
    return constDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcDefs createProcDefs()
  {
    ProcDefsImpl procDefs = new ProcDefsImpl();
    return procDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcDef createProcDef()
  {
    ProcDefImpl procDef = new ProcDefImpl();
    return procDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StautDefs createStautDefs()
  {
    StautDefsImpl stautDefs = new StautDefsImpl();
    return stautDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StautDef createStautDef()
  {
    StautDefImpl stautDef = new StautDefImpl();
    return stautDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChannelDefs createChannelDefs()
  {
    ChannelDefsImpl channelDefs = new ChannelDefsImpl();
    return channelDefs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChannelDef createChannelDef()
  {
    ChannelDefImpl channelDef = new ChannelDefImpl();
    return channelDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModelDef createModelDef()
  {
    ModelDefImpl modelDef = new ModelDefImpl();
    return modelDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MapperDef createMapperDef()
  {
    MapperDefImpl mapperDef = new MapperDefImpl();
    return mapperDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CnectDef createCnectDef()
  {
    CnectDefImpl cnectDef = new CnectDefImpl();
    return cnectDef;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StautItems createStautItems()
  {
    StautItemsImpl stautItems = new StautItemsImpl();
    return stautItems;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StateItem createStateItem()
  {
    StateItemImpl stateItem = new StateItemImpl();
    return stateItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VarItem createVarItem()
  {
    VarItemImpl varItem = new VarItemImpl();
    return varItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public InitItem createInitItem()
  {
    InitItemImpl initItem = new InitItemImpl();
    return initItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TransItem createTransItem()
  {
    TransItemImpl transItem = new TransItemImpl();
    return transItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Transition createTransition()
  {
    TransitionImpl transition = new TransitionImpl();
    return transition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public UpdateList createUpdateList()
  {
    UpdateListImpl updateList = new UpdateListImpl();
    return updateList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Update createUpdate()
  {
    UpdateImpl update = new UpdateImpl();
    return update;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public MapperName createMapperName()
  {
    MapperNameImpl mapperName = new MapperNameImpl();
    return mapperName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeConstructorList createNeConstructorList()
  {
    NeConstructorListImpl neConstructorList = new NeConstructorListImpl();
    return neConstructorList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Constructor createConstructor()
  {
    ConstructorImpl constructor = new ConstructorImpl();
    return constructor;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeFieldList createNeFieldList()
  {
    NeFieldListImpl neFieldList = new NeFieldListImpl();
    return neFieldList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Fields createFields()
  {
    FieldsImpl fields = new FieldsImpl();
    return fields;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeFieldNameList createNeFieldNameList()
  {
    NeFieldNameListImpl neFieldNameList = new NeFieldNameListImpl();
    return neFieldNameList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FieldName createFieldName()
  {
    FieldNameImpl fieldName = new FieldNameImpl();
    return fieldName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ExitDecl createExitDecl()
  {
    ExitDeclImpl exitDecl = new ExitDeclImpl();
    return exitDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ModelName createModelName()
  {
    ModelNameImpl modelName = new ModelNameImpl();
    return modelName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConnectionItem createConnectionItem()
  {
    ConnectionItemImpl connectionItem = new ConnectionItemImpl();
    return connectionItem;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConnectionOut createConnectionOut()
  {
    ConnectionOutImpl connectionOut = new ConnectionOutImpl();
    return connectionOut;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConnectionIn createConnectionIn()
  {
    ConnectionInImpl connectionIn = new ConnectionInImpl();
    return connectionIn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Encoding createEncoding()
  {
    EncodingImpl encoding = new EncodingImpl();
    return encoding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Decoding createDecoding()
  {
    DecodingImpl decoding = new DecodingImpl();
    return decoding;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public PortNumber createPortNumber()
  {
    PortNumberImpl portNumber = new PortNumberImpl();
    return portNumber;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public HostName createHostName()
  {
    HostNameImpl hostName = new HostNameImpl();
    return hostName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public StautName createStautName()
  {
    StautNameImpl stautName = new StautNameImpl();
    return stautName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChannelDefName createChannelDefName()
  {
    ChannelDefNameImpl channelDefName = new ChannelDefNameImpl();
    return channelDefName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcName createProcName()
  {
    ProcNameImpl procName = new ProcNameImpl();
    return procName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public CnectName createCnectName()
  {
    CnectNameImpl cnectName = new CnectNameImpl();
    return cnectName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeVarsDeclarationList createNeVarsDeclarationList()
  {
    NeVarsDeclarationListImpl neVarsDeclarationList = new NeVarsDeclarationListImpl();
    return neVarsDeclarationList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VarsDeclaration createVarsDeclaration()
  {
    VarsDeclarationImpl varsDeclaration = new VarsDeclarationImpl();
    return varsDeclaration;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeVarDeclList createNeVarDeclList()
  {
    NeVarDeclListImpl neVarDeclList = new NeVarDeclListImpl();
    return neVarDeclList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VarsDecl createVarsDecl()
  {
    VarsDeclImpl varsDecl = new VarsDeclImpl();
    return varsDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeChannelsDeclList createNeChannelsDeclList()
  {
    NeChannelsDeclListImpl neChannelsDeclList = new NeChannelsDeclListImpl();
    return neChannelsDeclList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChannelsDecl createChannelsDecl()
  {
    ChannelsDeclImpl channelsDecl = new ChannelsDeclImpl();
    return channelsDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeTypeNameList createNeTypeNameList()
  {
    NeTypeNameListImpl neTypeNameList = new NeTypeNameListImpl();
    return neTypeNameList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeName createTypeName()
  {
    TypeNameImpl typeName = new TypeNameImpl();
    return typeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeChannelNameList createNeChannelNameList()
  {
    NeChannelNameListImpl neChannelNameList = new NeChannelNameListImpl();
    return neChannelNameList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeIdNameList createNeIdNameList()
  {
    NeIdNameListImpl neIdNameList = new NeIdNameListImpl();
    return neIdNameList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public IdName createIdName()
  {
    IdNameImpl idName = new IdNameImpl();
    return idName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChannelName createChannelName()
  {
    ChannelNameImpl channelName = new ChannelNameImpl();
    return channelName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeVarNameList createNeVarNameList()
  {
    NeVarNameListImpl neVarNameList = new NeVarNameListImpl();
    return neVarNameList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VarName createVarName()
  {
    VarNameImpl varName = new VarNameImpl();
    return varName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviour createProcessBehaviour()
  {
    ProcessBehaviourImpl processBehaviour = new ProcessBehaviourImpl();
    return processBehaviour;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcCall createProcCall()
  {
    ProcCallImpl procCall = new ProcCallImpl();
    return procCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeValExprList createNeValExprList()
  {
    NeValExprListImpl neValExprList = new NeValExprListImpl();
    return neValExprList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourBracket createProcessBehaviourBracket()
  {
    ProcessBehaviourBracketImpl processBehaviourBracket = new ProcessBehaviourBracketImpl();
    return processBehaviourBracket;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourHide createProcessBehaviourHide()
  {
    ProcessBehaviourHideImpl processBehaviourHide = new ProcessBehaviourHideImpl();
    return processBehaviourHide;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourLet createProcessBehaviourLet()
  {
    ProcessBehaviourLetImpl processBehaviourLet = new ProcessBehaviourLetImpl();
    return processBehaviourLet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourSequence createProcessBehaviourSequence()
  {
    ProcessBehaviourSequenceImpl processBehaviourSequence = new ProcessBehaviourSequenceImpl();
    return processBehaviourSequence;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourGuarded createProcessBehaviourGuarded()
  {
    ProcessBehaviourGuardedImpl processBehaviourGuarded = new ProcessBehaviourGuardedImpl();
    return processBehaviourGuarded;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourStop createProcessBehaviourStop()
  {
    ProcessBehaviourStopImpl processBehaviourStop = new ProcessBehaviourStopImpl();
    return processBehaviourStop;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SynchronizedChannels createSynchronizedChannels()
  {
    SynchronizedChannelsImpl synchronizedChannels = new SynchronizedChannelsImpl();
    return synchronizedChannels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConditionalCommunications createConditionalCommunications()
  {
    ConditionalCommunicationsImpl conditionalCommunications = new ConditionalCommunicationsImpl();
    return conditionalCommunications;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Communications createCommunications()
  {
    CommunicationsImpl communications = new CommunicationsImpl();
    return communications;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Communication createCommunication()
  {
    CommunicationImpl communication = new CommunicationImpl();
    return communication;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ChannelOffer createChannelOffer()
  {
    ChannelOfferImpl channelOffer = new ChannelOfferImpl();
    return channelOffer;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Condition createCondition()
  {
    ConditionImpl condition = new ConditionImpl();
    return condition;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public Assignment createAssignment()
  {
    AssignmentImpl assignment = new AssignmentImpl();
    return assignment;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public VarDecl createVarDecl()
  {
    VarDeclImpl varDecl = new VarDeclImpl();
    return varDecl;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExpr createValExpr()
  {
    ValExprImpl valExpr = new ValExprImpl();
    return valExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExpr2 createValExpr2()
  {
    ValExpr2Impl valExpr2 = new ValExpr2Impl();
    return valExpr2;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprUnaryOperator createValExprUnaryOperator()
  {
    ValExprUnaryOperatorImpl valExprUnaryOperator = new ValExprUnaryOperatorImpl();
    return valExprUnaryOperator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public SmallIdName createSmallIdName()
  {
    SmallIdNameImpl smallIdName = new SmallIdNameImpl();
    return smallIdName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprError createValExprError()
  {
    ValExprErrorImpl valExprError = new ValExprErrorImpl();
    return valExprError;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprIte createValExprIte()
  {
    ValExprIteImpl valExprIte = new ValExprIteImpl();
    return valExprIte;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprLet createValExprLet()
  {
    ValExprLetImpl valExprLet = new ValExprLetImpl();
    return valExprLet;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprBracket createValExprBracket()
  {
    ValExprBracketImpl valExprBracket = new ValExprBracketImpl();
    return valExprBracket;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprRegex createValExprRegex()
  {
    ValExprRegexImpl valExprRegex = new ValExprRegexImpl();
    return valExprRegex;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprString createValExprString()
  {
    ValExprStringImpl valExprString = new ValExprStringImpl();
    return valExprString;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprInteger createValExprInteger()
  {
    ValExprIntegerImpl valExprInteger = new ValExprIntegerImpl();
    return valExprInteger;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprContructorCall createValExprContructorCall()
  {
    ValExprContructorCallImpl valExprContructorCall = new ValExprContructorCallImpl();
    return valExprContructorCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprFunctionCall createValExprFunctionCall()
  {
    ValExprFunctionCallImpl valExprFunctionCall = new ValExprFunctionCallImpl();
    return valExprFunctionCall;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprVar createValExprVar()
  {
    ValExprVarImpl valExprVar = new ValExprVarImpl();
    return valExprVar;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprConst createValExprConst()
  {
    ValExprConstImpl valExprConst = new ValExprConstImpl();
    return valExprConst;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConstructorName createConstructorName()
  {
    ConstructorNameImpl constructorName = new ConstructorNameImpl();
    return constructorName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FuncName createFuncName()
  {
    FuncNameImpl funcName = new FuncNameImpl();
    return funcName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ConstName createConstName()
  {
    ConstNameImpl constName = new ConstNameImpl();
    return constName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourEnable createProcessBehaviourEnable()
  {
    ProcessBehaviourEnableImpl processBehaviourEnable = new ProcessBehaviourEnableImpl();
    return processBehaviourEnable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourEnableAccept createProcessBehaviourEnableAccept()
  {
    ProcessBehaviourEnableAcceptImpl processBehaviourEnableAccept = new ProcessBehaviourEnableAcceptImpl();
    return processBehaviourEnableAccept;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourDisable createProcessBehaviourDisable()
  {
    ProcessBehaviourDisableImpl processBehaviourDisable = new ProcessBehaviourDisableImpl();
    return processBehaviourDisable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourInterrupt createProcessBehaviourInterrupt()
  {
    ProcessBehaviourInterruptImpl processBehaviourInterrupt = new ProcessBehaviourInterruptImpl();
    return processBehaviourInterrupt;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourSynchronized createProcessBehaviourSynchronized()
  {
    ProcessBehaviourSynchronizedImpl processBehaviourSynchronized = new ProcessBehaviourSynchronizedImpl();
    return processBehaviourSynchronized;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourParallel createProcessBehaviourParallel()
  {
    ProcessBehaviourParallelImpl processBehaviourParallel = new ProcessBehaviourParallelImpl();
    return processBehaviourParallel;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourSynchronizeChannels createProcessBehaviourSynchronizeChannels()
  {
    ProcessBehaviourSynchronizeChannelsImpl processBehaviourSynchronizeChannels = new ProcessBehaviourSynchronizeChannelsImpl();
    return processBehaviourSynchronizeChannels;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ProcessBehaviourChoice createProcessBehaviourChoice()
  {
    ProcessBehaviourChoiceImpl processBehaviourChoice = new ProcessBehaviourChoiceImpl();
    return processBehaviourChoice;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprOperator createValExprOperator()
  {
    ValExprOperatorImpl valExprOperator = new ValExprOperatorImpl();
    return valExprOperator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public ValExprTest createValExprTest()
  {
    ValExprTestImpl valExprTest = new ValExprTestImpl();
    return valExprTest;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TorXakisDslPackage getTorXakisDslPackage()
  {
    return (TorXakisDslPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static TorXakisDslPackage getPackage()
  {
    return TorXakisDslPackage.eINSTANCE;
  }

} //TorXakisDslFactoryImpl
