/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl.impl;

import nl.tno.torxakis.language.torXakisDsl.FuncName;
import nl.tno.torxakis.language.torXakisDsl.NeValExprList;
import nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage;
import nl.tno.torxakis.language.torXakisDsl.ValExprFunctionCall;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Val Expr Function Call</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ValExprFunctionCallImpl#getName <em>Name</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.ValExprFunctionCallImpl#getNeValExprList <em>Ne Val Expr List</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ValExprFunctionCallImpl extends ValExpr2Impl implements ValExprFunctionCall
{
  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected FuncName name;

  /**
   * The cached value of the '{@link #getNeValExprList() <em>Ne Val Expr List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNeValExprList()
   * @generated
   * @ordered
   */
  protected NeValExprList neValExprList;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ValExprFunctionCallImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TorXakisDslPackage.Literals.VAL_EXPR_FUNCTION_CALL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public FuncName getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetName(FuncName newName, NotificationChain msgs)
  {
    FuncName oldName = name;
    name = newName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NAME, oldName, newName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(FuncName newName)
  {
    if (newName != name)
    {
      NotificationChain msgs = null;
      if (name != null)
        msgs = ((InternalEObject)name).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NAME, null, msgs);
      if (newName != null)
        msgs = ((InternalEObject)newName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NAME, null, msgs);
      msgs = basicSetName(newName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NAME, newName, newName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeValExprList getNeValExprList()
  {
    return neValExprList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNeValExprList(NeValExprList newNeValExprList, NotificationChain msgs)
  {
    NeValExprList oldNeValExprList = neValExprList;
    neValExprList = newNeValExprList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NE_VAL_EXPR_LIST, oldNeValExprList, newNeValExprList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNeValExprList(NeValExprList newNeValExprList)
  {
    if (newNeValExprList != neValExprList)
    {
      NotificationChain msgs = null;
      if (neValExprList != null)
        msgs = ((InternalEObject)neValExprList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NE_VAL_EXPR_LIST, null, msgs);
      if (newNeValExprList != null)
        msgs = ((InternalEObject)newNeValExprList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NE_VAL_EXPR_LIST, null, msgs);
      msgs = basicSetNeValExprList(newNeValExprList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NE_VAL_EXPR_LIST, newNeValExprList, newNeValExprList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NAME:
        return basicSetName(null, msgs);
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NE_VAL_EXPR_LIST:
        return basicSetNeValExprList(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NAME:
        return getName();
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NE_VAL_EXPR_LIST:
        return getNeValExprList();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NAME:
        setName((FuncName)newValue);
        return;
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NE_VAL_EXPR_LIST:
        setNeValExprList((NeValExprList)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NAME:
        setName((FuncName)null);
        return;
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NE_VAL_EXPR_LIST:
        setNeValExprList((NeValExprList)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NAME:
        return name != null;
      case TorXakisDslPackage.VAL_EXPR_FUNCTION_CALL__NE_VAL_EXPR_LIST:
        return neValExprList != null;
    }
    return super.eIsSet(featureID);
  }

} //ValExprFunctionCallImpl
