/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl.impl;

import nl.tno.torxakis.language.torXakisDsl.NeVarNameList;
import nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage;
import nl.tno.torxakis.language.torXakisDsl.TypeName;
import nl.tno.torxakis.language.torXakisDsl.VarsDecl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Vars Decl</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.VarsDeclImpl#getNeVarNameList <em>Ne Var Name List</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.impl.VarsDeclImpl#getTypeName <em>Type Name</em>}</li>
 * </ul>
 *
 * @generated
 */
public class VarsDeclImpl extends MinimalEObjectImpl.Container implements VarsDecl
{
  /**
   * The cached value of the '{@link #getNeVarNameList() <em>Ne Var Name List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getNeVarNameList()
   * @generated
   * @ordered
   */
  protected NeVarNameList neVarNameList;

  /**
   * The cached value of the '{@link #getTypeName() <em>Type Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getTypeName()
   * @generated
   * @ordered
   */
  protected TypeName typeName;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected VarsDeclImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TorXakisDslPackage.Literals.VARS_DECL;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NeVarNameList getNeVarNameList()
  {
    return neVarNameList;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetNeVarNameList(NeVarNameList newNeVarNameList, NotificationChain msgs)
  {
    NeVarNameList oldNeVarNameList = neVarNameList;
    neVarNameList = newNeVarNameList;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.VARS_DECL__NE_VAR_NAME_LIST, oldNeVarNameList, newNeVarNameList);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setNeVarNameList(NeVarNameList newNeVarNameList)
  {
    if (newNeVarNameList != neVarNameList)
    {
      NotificationChain msgs = null;
      if (neVarNameList != null)
        msgs = ((InternalEObject)neVarNameList).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.VARS_DECL__NE_VAR_NAME_LIST, null, msgs);
      if (newNeVarNameList != null)
        msgs = ((InternalEObject)newNeVarNameList).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.VARS_DECL__NE_VAR_NAME_LIST, null, msgs);
      msgs = basicSetNeVarNameList(newNeVarNameList, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.VARS_DECL__NE_VAR_NAME_LIST, newNeVarNameList, newNeVarNameList));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TypeName getTypeName()
  {
    return typeName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetTypeName(TypeName newTypeName, NotificationChain msgs)
  {
    TypeName oldTypeName = typeName;
    typeName = newTypeName;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.VARS_DECL__TYPE_NAME, oldTypeName, newTypeName);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setTypeName(TypeName newTypeName)
  {
    if (newTypeName != typeName)
    {
      NotificationChain msgs = null;
      if (typeName != null)
        msgs = ((InternalEObject)typeName).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.VARS_DECL__TYPE_NAME, null, msgs);
      if (newTypeName != null)
        msgs = ((InternalEObject)newTypeName).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TorXakisDslPackage.VARS_DECL__TYPE_NAME, null, msgs);
      msgs = basicSetTypeName(newTypeName, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TorXakisDslPackage.VARS_DECL__TYPE_NAME, newTypeName, newTypeName));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VARS_DECL__NE_VAR_NAME_LIST:
        return basicSetNeVarNameList(null, msgs);
      case TorXakisDslPackage.VARS_DECL__TYPE_NAME:
        return basicSetTypeName(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VARS_DECL__NE_VAR_NAME_LIST:
        return getNeVarNameList();
      case TorXakisDslPackage.VARS_DECL__TYPE_NAME:
        return getTypeName();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VARS_DECL__NE_VAR_NAME_LIST:
        setNeVarNameList((NeVarNameList)newValue);
        return;
      case TorXakisDslPackage.VARS_DECL__TYPE_NAME:
        setTypeName((TypeName)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VARS_DECL__NE_VAR_NAME_LIST:
        setNeVarNameList((NeVarNameList)null);
        return;
      case TorXakisDslPackage.VARS_DECL__TYPE_NAME:
        setTypeName((TypeName)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TorXakisDslPackage.VARS_DECL__NE_VAR_NAME_LIST:
        return neVarNameList != null;
      case TorXakisDslPackage.VARS_DECL__TYPE_NAME:
        return typeName != null;
    }
    return super.eIsSet(featureID);
  }

} //VarsDeclImpl
