/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Communication</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.Communication#getChannelName <em>Channel Name</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.Communication#getExit <em>Exit</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.Communication#getChannelOffers <em>Channel Offers</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getCommunication()
 * @model
 * @generated
 */
public interface Communication extends EObject
{
  /**
   * Returns the value of the '<em><b>Channel Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channel Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channel Name</em>' containment reference.
   * @see #setChannelName(ChannelName)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getCommunication_ChannelName()
   * @model containment="true"
   * @generated
   */
  ChannelName getChannelName();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.Communication#getChannelName <em>Channel Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Channel Name</em>' containment reference.
   * @see #getChannelName()
   * @generated
   */
  void setChannelName(ChannelName value);

  /**
   * Returns the value of the '<em><b>Exit</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exit</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exit</em>' attribute.
   * @see #setExit(String)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getCommunication_Exit()
   * @model
   * @generated
   */
  String getExit();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.Communication#getExit <em>Exit</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exit</em>' attribute.
   * @see #getExit()
   * @generated
   */
  void setExit(String value);

  /**
   * Returns the value of the '<em><b>Channel Offers</b></em>' containment reference list.
   * The list contents are of type {@link nl.tno.torxakis.language.torXakisDsl.ChannelOffer}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channel Offers</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channel Offers</em>' containment reference list.
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getCommunication_ChannelOffers()
   * @model containment="true"
   * @generated
   */
  EList<ChannelOffer> getChannelOffers();

} // Communication
