/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connection Out</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ConnectionOut#getChannelsDecl <em>Channels Decl</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ConnectionOut#getHostName <em>Host Name</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ConnectionOut#getPortNumber <em>Port Number</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getConnectionOut()
 * @model
 * @generated
 */
public interface ConnectionOut extends ConnectionItem
{
  /**
   * Returns the value of the '<em><b>Channels Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Channels Decl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Channels Decl</em>' containment reference.
   * @see #setChannelsDecl(ChannelsDecl)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getConnectionOut_ChannelsDecl()
   * @model containment="true"
   * @generated
   */
  ChannelsDecl getChannelsDecl();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ConnectionOut#getChannelsDecl <em>Channels Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Channels Decl</em>' containment reference.
   * @see #getChannelsDecl()
   * @generated
   */
  void setChannelsDecl(ChannelsDecl value);

  /**
   * Returns the value of the '<em><b>Host Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Host Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Host Name</em>' containment reference.
   * @see #setHostName(HostName)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getConnectionOut_HostName()
   * @model containment="true"
   * @generated
   */
  HostName getHostName();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ConnectionOut#getHostName <em>Host Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Host Name</em>' containment reference.
   * @see #getHostName()
   * @generated
   */
  void setHostName(HostName value);

  /**
   * Returns the value of the '<em><b>Port Number</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Port Number</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Port Number</em>' containment reference.
   * @see #setPortNumber(PortNumber)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getConnectionOut_PortNumber()
   * @model containment="true"
   * @generated
   */
  PortNumber getPortNumber();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ConnectionOut#getPortNumber <em>Port Number</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Port Number</em>' containment reference.
   * @see #getPortNumber()
   * @generated
   */
  void setPortNumber(PortNumber value);

} // ConnectionOut
