/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Connection Item</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getConnectionItem()
 * @model
 * @generated
 */
public interface ConnectionItem extends EObject
{
} // ConnectionItem
