/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Model Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ModelDef#getModelName <em>Model Name</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ModelDef#getNeInputChannelNameList <em>Ne Input Channel Name List</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ModelDef#getNeOutputChannelNameList <em>Ne Output Channel Name List</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ModelDef#getProcessBehaviour <em>Process Behaviour</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getModelDef()
 * @model
 * @generated
 */
public interface ModelDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Model Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Model Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Model Name</em>' containment reference.
   * @see #setModelName(ModelName)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getModelDef_ModelName()
   * @model containment="true"
   * @generated
   */
  ModelName getModelName();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ModelDef#getModelName <em>Model Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Model Name</em>' containment reference.
   * @see #getModelName()
   * @generated
   */
  void setModelName(ModelName value);

  /**
   * Returns the value of the '<em><b>Ne Input Channel Name List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ne Input Channel Name List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ne Input Channel Name List</em>' containment reference.
   * @see #setNeInputChannelNameList(NeChannelNameList)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getModelDef_NeInputChannelNameList()
   * @model containment="true"
   * @generated
   */
  NeChannelNameList getNeInputChannelNameList();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ModelDef#getNeInputChannelNameList <em>Ne Input Channel Name List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ne Input Channel Name List</em>' containment reference.
   * @see #getNeInputChannelNameList()
   * @generated
   */
  void setNeInputChannelNameList(NeChannelNameList value);

  /**
   * Returns the value of the '<em><b>Ne Output Channel Name List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ne Output Channel Name List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ne Output Channel Name List</em>' containment reference.
   * @see #setNeOutputChannelNameList(NeChannelNameList)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getModelDef_NeOutputChannelNameList()
   * @model containment="true"
   * @generated
   */
  NeChannelNameList getNeOutputChannelNameList();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ModelDef#getNeOutputChannelNameList <em>Ne Output Channel Name List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ne Output Channel Name List</em>' containment reference.
   * @see #getNeOutputChannelNameList()
   * @generated
   */
  void setNeOutputChannelNameList(NeChannelNameList value);

  /**
   * Returns the value of the '<em><b>Process Behaviour</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Process Behaviour</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process Behaviour</em>' containment reference.
   * @see #setProcessBehaviour(ProcessBehaviour)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getModelDef_ProcessBehaviour()
   * @model containment="true"
   * @generated
   */
  ProcessBehaviour getProcessBehaviour();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ModelDef#getProcessBehaviour <em>Process Behaviour</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Process Behaviour</em>' containment reference.
   * @see #getProcessBehaviour()
   * @generated
   */
  void setProcessBehaviour(ProcessBehaviour value);

} // ModelDef
