/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ne Var Decl List</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.NeVarDeclList#getVarsDecls <em>Vars Decls</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getNeVarDeclList()
 * @model
 * @generated
 */
public interface NeVarDeclList extends EObject
{
  /**
   * Returns the value of the '<em><b>Vars Decls</b></em>' containment reference list.
   * The list contents are of type {@link nl.tno.torxakis.language.torXakisDsl.VarsDecl}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Vars Decls</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Vars Decls</em>' containment reference list.
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getNeVarDeclList_VarsDecls()
   * @model containment="true"
   * @generated
   */
  EList<VarsDecl> getVarsDecls();

} // NeVarDeclList
