/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Behaviour Stop</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcessBehaviourStop#getStop <em>Stop</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcessBehaviourStop()
 * @model
 * @generated
 */
public interface ProcessBehaviourStop extends ProcessBehaviour
{
  /**
   * Returns the value of the '<em><b>Stop</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Stop</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Stop</em>' attribute.
   * @see #setStop(String)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcessBehaviourStop_Stop()
   * @model
   * @generated
   */
  String getStop();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcessBehaviourStop#getStop <em>Stop</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Stop</em>' attribute.
   * @see #getStop()
   * @generated
   */
  void setStop(String value);

} // ProcessBehaviourStop
