/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Proc Def</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getName <em>Name</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getNeChannelDeclList <em>Ne Channel Decl List</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getNeVarDeclList <em>Ne Var Decl List</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getExitDecl <em>Exit Decl</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getProcessBehaviour <em>Process Behaviour</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcDef()
 * @model
 * @generated
 */
public interface ProcDef extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(ProcName)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcDef_Name()
   * @model containment="true"
   * @generated
   */
  ProcName getName();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(ProcName value);

  /**
   * Returns the value of the '<em><b>Ne Channel Decl List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ne Channel Decl List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ne Channel Decl List</em>' containment reference.
   * @see #setNeChannelDeclList(NeChannelsDeclList)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcDef_NeChannelDeclList()
   * @model containment="true"
   * @generated
   */
  NeChannelsDeclList getNeChannelDeclList();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getNeChannelDeclList <em>Ne Channel Decl List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ne Channel Decl List</em>' containment reference.
   * @see #getNeChannelDeclList()
   * @generated
   */
  void setNeChannelDeclList(NeChannelsDeclList value);

  /**
   * Returns the value of the '<em><b>Ne Var Decl List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ne Var Decl List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ne Var Decl List</em>' containment reference.
   * @see #setNeVarDeclList(NeVarDeclList)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcDef_NeVarDeclList()
   * @model containment="true"
   * @generated
   */
  NeVarDeclList getNeVarDeclList();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getNeVarDeclList <em>Ne Var Decl List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ne Var Decl List</em>' containment reference.
   * @see #getNeVarDeclList()
   * @generated
   */
  void setNeVarDeclList(NeVarDeclList value);

  /**
   * Returns the value of the '<em><b>Exit Decl</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Exit Decl</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exit Decl</em>' containment reference.
   * @see #setExitDecl(ExitDecl)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcDef_ExitDecl()
   * @model containment="true"
   * @generated
   */
  ExitDecl getExitDecl();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getExitDecl <em>Exit Decl</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Exit Decl</em>' containment reference.
   * @see #getExitDecl()
   * @generated
   */
  void setExitDecl(ExitDecl value);

  /**
   * Returns the value of the '<em><b>Process Behaviour</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Process Behaviour</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process Behaviour</em>' containment reference.
   * @see #setProcessBehaviour(ProcessBehaviour)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcDef_ProcessBehaviour()
   * @model containment="true"
   * @generated
   */
  ProcessBehaviour getProcessBehaviour();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcDef#getProcessBehaviour <em>Process Behaviour</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Process Behaviour</em>' containment reference.
   * @see #getProcessBehaviour()
   * @generated
   */
  void setProcessBehaviour(ProcessBehaviour value);

} // ProcDef
