/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process Behaviour Enable Accept</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcessBehaviourEnableAccept#getLeft <em>Left</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcessBehaviourEnableAccept#getVarDecls <em>Var Decls</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcessBehaviourEnableAccept#getVarNames <em>Var Names</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcessBehaviourEnableAccept#getValExprs <em>Val Exprs</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcessBehaviourEnableAccept#getRight <em>Right</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcessBehaviourEnableAccept()
 * @model
 * @generated
 */
public interface ProcessBehaviourEnableAccept extends ProcessBehaviour
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Left</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(ProcessBehaviour)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcessBehaviourEnableAccept_Left()
   * @model containment="true"
   * @generated
   */
  ProcessBehaviour getLeft();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcessBehaviourEnableAccept#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(ProcessBehaviour value);

  /**
   * Returns the value of the '<em><b>Var Decls</b></em>' containment reference list.
   * The list contents are of type {@link nl.tno.torxakis.language.torXakisDsl.VarDecl}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Decls</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Decls</em>' containment reference list.
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcessBehaviourEnableAccept_VarDecls()
   * @model containment="true"
   * @generated
   */
  EList<VarDecl> getVarDecls();

  /**
   * Returns the value of the '<em><b>Var Names</b></em>' containment reference list.
   * The list contents are of type {@link nl.tno.torxakis.language.torXakisDsl.VarName}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Var Names</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Var Names</em>' containment reference list.
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcessBehaviourEnableAccept_VarNames()
   * @model containment="true"
   * @generated
   */
  EList<VarName> getVarNames();

  /**
   * Returns the value of the '<em><b>Val Exprs</b></em>' containment reference list.
   * The list contents are of type {@link nl.tno.torxakis.language.torXakisDsl.ValExpr}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Val Exprs</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val Exprs</em>' containment reference list.
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcessBehaviourEnableAccept_ValExprs()
   * @model containment="true"
   * @generated
   */
  EList<ValExpr> getValExprs();

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Right</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(ProcessBehaviour)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcessBehaviourEnableAccept_Right()
   * @model containment="true"
   * @generated
   */
  ProcessBehaviour getRight();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcessBehaviourEnableAccept#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(ProcessBehaviour value);

} // ProcessBehaviourEnableAccept
