/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Proc Call</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcCall#getName <em>Name</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcCall#getNeChannelNameList <em>Ne Channel Name List</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ProcCall#getNeValExprList <em>Ne Val Expr List</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcCall()
 * @model
 * @generated
 */
public interface ProcCall extends ProcessBehaviour
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' containment reference.
   * @see #setName(ProcName)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcCall_Name()
   * @model containment="true"
   * @generated
   */
  ProcName getName();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcCall#getName <em>Name</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' containment reference.
   * @see #getName()
   * @generated
   */
  void setName(ProcName value);

  /**
   * Returns the value of the '<em><b>Ne Channel Name List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ne Channel Name List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ne Channel Name List</em>' containment reference.
   * @see #setNeChannelNameList(NeChannelNameList)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcCall_NeChannelNameList()
   * @model containment="true"
   * @generated
   */
  NeChannelNameList getNeChannelNameList();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcCall#getNeChannelNameList <em>Ne Channel Name List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ne Channel Name List</em>' containment reference.
   * @see #getNeChannelNameList()
   * @generated
   */
  void setNeChannelNameList(NeChannelNameList value);

  /**
   * Returns the value of the '<em><b>Ne Val Expr List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ne Val Expr List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ne Val Expr List</em>' containment reference.
   * @see #setNeValExprList(NeValExprList)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getProcCall_NeValExprList()
   * @model containment="true"
   * @generated
   */
  NeValExprList getNeValExprList();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ProcCall#getNeValExprList <em>Ne Val Expr List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ne Val Expr List</em>' containment reference.
   * @see #getNeValExprList()
   * @generated
   */
  void setNeValExprList(NeValExprList value);

} // ProcCall
