/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Val Expr</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getValExpr()
 * @model
 * @generated
 */
public interface ValExpr extends EObject
{
} // ValExpr
