/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Val Expr Error</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ValExprError#getError <em>Error</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getValExprError()
 * @model
 * @generated
 */
public interface ValExprError extends ValExpr2
{
  /**
   * Returns the value of the '<em><b>Error</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Error</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Error</em>' attribute.
   * @see #setError(String)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getValExprError_Error()
   * @model
   * @generated
   */
  String getError();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ValExprError#getError <em>Error</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Error</em>' attribute.
   * @see #getError()
   * @generated
   */
  void setError(String value);

} // ValExprError
