/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Val Expr Unary Operator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ValExprUnaryOperator#getOperator <em>Operator</em>}</li>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.ValExprUnaryOperator#getValExpr <em>Val Expr</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getValExprUnaryOperator()
 * @model
 * @generated
 */
public interface ValExprUnaryOperator extends ValExpr2
{
  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Operator</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see #setOperator(String)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getValExprUnaryOperator_Operator()
   * @model
   * @generated
   */
  String getOperator();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ValExprUnaryOperator#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see #getOperator()
   * @generated
   */
  void setOperator(String value);

  /**
   * Returns the value of the '<em><b>Val Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Val Expr</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val Expr</em>' containment reference.
   * @see #setValExpr(ValExpr2)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getValExprUnaryOperator_ValExpr()
   * @model containment="true"
   * @generated
   */
  ValExpr2 getValExpr();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.ValExprUnaryOperator#getValExpr <em>Val Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val Expr</em>' containment reference.
   * @see #getValExpr()
   * @generated
   */
  void setValExpr(ValExpr2 value);

} // ValExprUnaryOperator
