/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Val Expr2</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getValExpr2()
 * @model
 * @generated
 */
public interface ValExpr2 extends ValExpr
{
} // ValExpr2
