/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.torXakisDsl;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var Item</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link nl.tno.torxakis.language.torXakisDsl.VarItem#getNeVarsDelarationList <em>Ne Vars Delaration List</em>}</li>
 * </ul>
 *
 * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getVarItem()
 * @model
 * @generated
 */
public interface VarItem extends EObject
{
  /**
   * Returns the value of the '<em><b>Ne Vars Delaration List</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Ne Vars Delaration List</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ne Vars Delaration List</em>' containment reference.
   * @see #setNeVarsDelarationList(NeVarsDeclarationList)
   * @see nl.tno.torxakis.language.torXakisDsl.TorXakisDslPackage#getVarItem_NeVarsDelarationList()
   * @model containment="true"
   * @generated
   */
  NeVarsDeclarationList getNeVarsDelarationList();

  /**
   * Sets the value of the '{@link nl.tno.torxakis.language.torXakisDsl.VarItem#getNeVarsDelarationList <em>Ne Vars Delaration List</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ne Vars Delaration List</em>' containment reference.
   * @see #getNeVarsDelarationList()
   * @generated
   */
  void setNeVarsDelarationList(NeVarsDeclarationList value);

} // VarItem
