/**
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language;

import nl.tno.torxakis.language.TorXakisDslStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class TorXakisDslStandaloneSetup extends TorXakisDslStandaloneSetupGenerated {
  public static void doSetup() {
    TorXakisDslStandaloneSetup _torXakisDslStandaloneSetup = new TorXakisDslStandaloneSetup();
    _torXakisDslStandaloneSetup.createInjectorAndDoEMFRegistration();
  }
}
