/*
 * generated by Xtext 2.10.0
 */
package nl.tno.torxakis.language.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TorXakisDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("nl/tno/torxakis/language/parser/antlr/internal/InternalTorXakisDsl.tokens");
	}
}
